language: scala
scala:
  - 2.11.1
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
script: sbt ++$TRAVIS_SCALA_VERSION test "project clients" test "project bigClients" test "test-only longRunning.BenchSuite"
