language: scala
# Keep in sync by hand with build.sbt.
jdk:
  - openjdk7
sudo: false
# Caching setup from:
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
cache:
  directories:
    - $HOME/.sbt/boot
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
install:
  - travis_retry sbt update
script:
  - sbt test "project clients" "testOnly ilc.*" "project bigClients" "testOnly ilc.*" "project icfp2014" test

  # Tricks to avoid unnecessary cache updates, also from
  # http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
